---
title: "Used Car Price Predictions"
author: "Daniel Chang, Vo Nguyen, & Akib Hossain"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Link to Presentation Video:


```{r}
#Needed Packages
library(tidyverse)
library(caret)
library(naniar)
library(stringr)

#Load Data
car_details = Car_details_v3

```

## Exploratory Data Analysis #1
We first take a look at our dataset.
```{r null values, echo=FALSE}

head(car_details)
dim(car_details)

#Addressing Missing Data
vis_miss(car_details)
car_details = na.omit(car_details)
head(car_details)

car_details = na.omit(car_details)
car_details$brand = na.omit(car_details$brand)

# extract string to clean columns
car_details$brand = word(car_details$name, 1)
car_details$name = sub('^\\w+\\s', '', car_details$name)

# extract numbers
car_details$engine = as.numeric(gsub("([0-9]+).*$", "\\1", car_details$engine))
car_details$mileage = as.numeric(str_extract(car_details$mileage, "\\d*\\.*\\d"))

car_details$max_power = as.numeric(str_extract(car_details$max_power, "\\d*\\.*\\d"))

#Owner No Space
car_details$owner <- word(car_details$owner, 1)

```

```{r visuals, echo=FALSE}
## Mean Selling Price Line Plot
mean_price = car_details %>%
  select(year, selling_price) %>%
  group_by(year) %>%
  summarise(mean_price = mean(selling_price))
  
ggplot(mean_price, aes(x = year, y = mean_price)) +
  geom_line() +
  ggtitle("Mean Selling Price By Year")

## Fuel Count
fuel_count = car_details %>%
  group_by(fuel) %>%
  summarise(n = n())

ggplot(fuel_count, aes(x = fuel, y = n)) +
  geom_bar(stat='identity') +
  ggtitle("Fuel Count") +
  ylab("Fuel Count") + 
  xlab("Fuel")

## Brand Count
brand_count = car_details %>%
  group_by(brand) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

ggplot(brand_count, aes(x = brand, y = n)) +
  geom_bar(stat='identity') +
  ggtitle("Brand Count") + 
  coord_flip() +
  ylab("Brand Count") + 
  xlab("Brand")

## Histogram of Mileage
ggplot(car_details, aes(x = mileage)) +
  geom_histogram(bins = 40) +
  ggtitle("Histogram of Mileage")

## Histogram of Engine
ggplot(car_details, aes(x = engine)) +
  geom_histogram(bins = 10) +
  ggtitle("Histogram of Engine")

## Histogram of km_driven
ggplot(car_details, aes(x = km_driven)) +
  geom_histogram(bins = 10) +
  ggtitle("Histogram of Kilometers Driven")

## Popular Names
pop_name = car_details %>%
  group_by(name) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  head(5)

ggplot(pop_name, aes(x = name, y = n)) +
  geom_bar(stat='identity') +
  ggtitle("Name Count") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Name Count") + 
  xlab("Name")

## Selling Price vs Max Power
ggplot(car_details, aes(x = max_power, y = selling_price)) +
  geom_point() +
  ggtitle("Selling Price vs. Max Power") +
  xlab("Max Power") +
  ylab("Selling Price")
```

```{r visuals, echo=FALSE}
#Tradional MLR Model 1
model1 = lm(selling_price~year + km_driven + fuel+ seller_type + transmission + owner + mileage + engine + max_power + seats + brand,data=car_details)
summary(model1)

par(mfrow=c(2,2))
plot(model1)
par(mfrow=c(1,1))


#Tradional MLR Model 2 with Log Transformation
model2 = lm(log(selling_price)~year + km_driven + fuel+ seller_type + transmission + owner + mileage + engine + max_power + seats +brand,data=car_details)
summary(model2)

par(mfrow=c(2,2))
plot(model2)
par(mfrow=c(1,1))


#Tradional MLR Model 3 with Log Transformation & Interactions
model3 = lm(log(selling_price)~(year + log(km_driven) + fuel+ seller_type + transmission + owner + mileage + log(engine) + log(max_power) + log(seats) + brand)^2,data=car_details)
summary(model3)

par(mfrow=c(2,2))
plot(model3)
par(mfrow=c(1,1))

model5 = lm(log(selling_price)~seller_type + owner + log(max_power)+log(seats)+year:log(km_driven)+year:seller_type+year:owner+year:log(max_power)+year:log(seats)+log(km_driven):log(engine)+log(km_driven):log(max_power)+log(km_driven):log(seats)+fuel:seller_type,data=car_details)
summary(model5)

par(mfrow=c(2,2))
plot(model5)
par(mfrow=c(1,1))

#Tradional MLR Model 4 with Log Transformation & Interactions
model4 = lm(log(selling_price)~year + log(km_driven) + fuel+ seller_type + transmission + owner + mileage + log(engine) + log(max_power) + log(seats) + brand,data=car_details)
summary(model4)

par(mfrow=c(2,2))
plot(model4)
par(mfrow=c(1,1))


```

```{r}
#Check for Multicollinearity
library(car)
vif(model4)
```

```{r}
library(leaps)

trainIndex<-createDataPartition(car_details$selling_price,p=.8,list=F)  #p: proportion of data in train

training<-car_details[trainIndex,]
validate<-car_details[-trainIndex,]


reg.fwd=regsubsets(log(selling_price)~year + log(km_driven) + fuel+ seller_type + transmission + owner + mileage + log(engine) + log(max_power) + log(seats) + brand,data=car_details,method="forward",nvmax=30)
coef(reg.fwd,10)

reg.bwd=regsubsets(log(selling_price)~year + log(km_driven) + fuel+ seller_type + transmission + owner + mileage + log(engine) + log(max_power) + log(seats) + brand,data=car_details,method="backward",nvmax=20)
coef(reg.bwd,10)


#Creating a prediction function 
predict.regsubsets =function (object , newdata ,id ,...){
  form=as.formula (object$call [[2]])
  mat=model.matrix(form ,newdata )
  coefi=coef(object ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}


valMSE<-c()
#note my index, i, is to 20 since that is how many predictors I went up to during fwd selection
for (i in 1:20){
  predictions<-predict.regsubsets(object=reg.fwd,newdata=validate,id=i) 
  valMSE[i]<-mean((log(validate$selling_price)-predictions)^2)
}
par(mfrow=c(1,1))
plot(1:20,sqrt(valMSE),type="l",xlab="# of predictors",ylab="test vs train RMSE",ylim=c(0.3,.9))
index<-which(valMSE==min(valMSE))
points(index,sqrt(valMSE[index]),col="red",pch=10)

trainMSE<-summary(reg.fwd)$rss/nrow(training)
lines(1:20,sqrt(trainMSE),lty=3,col="blue")  

```

```{r}
#OLSRR 
set.seed(1234)
library(olsrr)


ols_step_forward_p(model4,prem = .05,details=TRUE)
ols_step_backward_p(model4,prem = .05,details=TRUE)
ols_step_both_p(model4,prem = .05,details=TRUE)


```

```{r}
library(caret)
set.seed(1234)

#K-fold in R
fitControl<-trainControl(method="repeatedcv",number=10,repeats=1) 

model4.fit <-train(log(selling_price)~seller_type + owner + log(max_power)+log(seats)+year:log(km_driven)+year:seller_type+year:owner+year:log(max_power)+year:log(seats)+log(km_driven):log(engine)+log(km_driven):log(max_power)+log(km_driven):log(seats)+fuel:seller_type,data=car_details,
                  method="glmnet",
                  trControl=fitControl
)


model4.fit
plot(model4.fit)

#Investigating Coefficients
opt.pen=model4.fit$finalModel$lambdaOpt #penalty term
coef(model4.fit$finalModel,opt.pen)

#Linear Regression
model4.fit2 <-train(log(selling_price)~seller_type + owner + log(max_power)+log(seats)+year:log(km_driven)+year:seller_type+year:owner+year:log(max_power)+year:log(seats)+log(km_driven):log(engine)+log(km_driven):log(max_power), data= car_details,
                  method="lm",
                  trControl=fitControl,
                
)


model4.fit2
plot(model4.fit2)

opt.pen<-model4.fit2$finalModel   #penalty term
coef(model4.fit2$finalModel)

#Ridge
model4.fit3 <-train(log(selling_price)~year + log(km_driven) + fuel+ seller_type + transmission + owner + mileage + log(engine) + log(max_power) + log(seats) + brand, data= car_details,
                  method="glmnet",
                  trControl=fitControl,
                  tuneGrid=expand.grid(data.frame(alpha=0,lambda=seq(0,.0001,0.001225234)))
)


model4.fit3
plot(model4.fit3)

opt.pen<-model4.fit3$finalModel$lambdaOpt   #penalty term
coef(model4.fit3$finalModel,opt.pen)

summary(lm(log(selling_price)~year + log(km_driven) + fuel+ seller_type + transmission + owner + mileage + log(engine) + log(max_power) + log(seats) + brand, data= car_details))
```

```{r}
#K Fold CV for Knn

#Setting k fold parameters
fitControl<-trainControl(method="repeatedcv",number=10,repeats=1) 

#training the model via 10fold cv
knn.fit<-train(log(selling_price)~seller_type + owner + log(max_power)+log(seats)+year:log(km_driven)+year:seller_type+year:owner+year:log(max_power)+year:log(seats)+log(km_driven):log(engine)+log(km_driven):log(max_power)+log(km_driven):log(seats)+fuel:seller_type,
                  data=car_details,
                  method="knn",
                  trControl=fitControl
)

plot(knn.fit)
knn.fit

#training the model via 10fold cv
knn.fit2<-train(log(selling_price)~seller_type + owner + log(max_power)+log(seats)+year:log(km_driven)+year:seller_type+year:owner+year:log(max_power)+year:log(seats)+log(km_driven):log(engine)+log(km_driven):log(max_power)+log(km_driven):log(seats)+fuel:seller_type,
                  data=car_details,
                  method="knn",
                  trControl=fitControl,
               tuneGrid=expand.grid(k=c(5:9))
)

plot(knn.fit2)
knn.fit2
```